### PR TITLE
Added Qr Code Scanner

### PR DESCRIPTION
**Pull request by prasantgupta52**
### Description

I have added the QR scanning page for the user to scan the invite qr and join the meeting

### Checklist

- [x] I am making a proper pull request, not spam.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

[Add Qr Code Scanner in join Meeting Section](https://github.com/ashavijit/Meetify/issues/28)

## Add relevant screenshot or video (if any)

image
image

### CODE REVIEW

**Comment by ashavijit** [comment]
@prasantgupta52 its fine working without eslint and prettier . please take the latest pull and then configure it with eslint and prettier . create a pr

**Comment by ashavijit** [comment]
`[19:18:54.056] Cloning github.com/ashavijit/Meetify (Branch: main, Commit: 836a06d)
[19:18:55.071] Cloning completed: 1.015s
[19:18:55.350] Looking up build cache...
[19:19:00.605] Build cache downloaded [64.66 MB]: 5028.193ms
[19:19:00.668] Running "vercel build"
[19:19:01.365] Vercel CLI 28.4.9
[19:19:01.414] WARN! Did you mean to deploy the subdirectory "build"? Use `vc --cwd build` instead.
[19:19:01.802] Installing dependencies...
[19:19:07.130] 
[19:19:07.130] added 5 packages in 5s
[19:19:07.131] 
[19:19:07.131] 212 packages are looking for funding
[19:19:07.131]   run `npm fund` for details
[19:19:07.170] Detected `package-lock.json` generated by npm 7+...
[19:19:07.170] Running "npm run build"
[19:19:07.575] 
[19:19:07.575] > client@0.1.0 build
[19:19:07.575] > react-scripts build
[19:19:07.575] 
[19:19:09.737] Creating an optimized production build...
[19:19:52.366] Failed to compile.
[19:19:52.366] 
[19:19:52.367] [eslint] 
[19:19:52.367] src/components/JoinCard.jsx
[19:19:52.368]   Line 36:15:  Replace `·type="text"·value={joininglink}·onChange={(e)·=>·{·setJoininglink(e.target.value)·}}·className="wd·form-control·text-black·px-2·py-1"·placeholder="Link·Here..!"·/>` with `⏎··········type="text"⏎··········value={joininglink}⏎··········onChange={(e)·=>·{⏎············setJoininglink(e.target.value);⏎··········}}⏎··········className="wd·form-control·text-black·px-2·py-1"⏎··········placeholder="Link·Here..!"⏎········/>⏎········`  prettier/prettier
[19:19:52.368]   Line 37:16:  Replace `·className="my-11·px-4·py-1·rounded-lg·border·border-danger"·onClick={joinroomusingid}>Join·Meeting` with `⏎··········className="my-11·px-4·py-1·rounded-lg·border·border-danger"⏎··········onClick={joinroomusingid}⏎········>⏎··········Join·Meeting⏎········`                                                                                                                                                                             prettier/prettier
[19:19:52.368]   Line 39:1:   Replace `········<button·className="my-11·mx-2·px-4·py-1·rounded-lg·border·border-danger"·>Scan·Invite·QR` with `··········<button·className="my-11·mx-2·px-4·py-1·rounded-lg·border·border-danger">⏎············Scan·Invite·QR⏎··········`                                                                                                                                                                                                           prettier/prettier
[19:19:52.368] 
[19:19:52.369] src/page/Scanqr.jsx
[19:19:52.369]   Line 1:44:    Replace `'react'` with `"react"`                                                                                                                                                                                                                                                                 prettier/prettier
[19:19:52.369]   Line 2:26:    Replace `'react-qr-reader'` with `"react-qr-reader"`                                                                                                                                                                                                                                             prettier/prettier
[19:19:52.370]   Line 6:23:    Delete `⏎`                                                                                                                                                                                                                                                                                       prettier/prettier
[19:19:52.370]   Line 23:4:    Insert `;`                                                                                                                                                                                                                                                                                       prettier/prettier
[19:19:52.371]   Line 26:7:    Delete `⏎`                                                                                                                                                                                                                                                                                       prettier/prettier
[19:19:52.371]   Line 29:13:   Replace `·className={`joinpage·flex·p-3·md:p-6·rounded·md:rounded-2xl·md:h-72·md:w-auto·w-full·group·bg-blue`}` with `⏎··········className={`joinpage·flex·p-3·md:p-6·rounded·md:rounded-2xl·md:h-72·md:w-auto·w-full·group·bg-blue`}⏎·······`                                                   prettier/prettier
[19:19:52.372]   Line 39:82:   Replace `⏎················Scan·QR-Code⏎··············` with `Scan·QR-Code`                                                                                                                                                                                                                       prettier/prettier
[19:19:52.372]   Line 42:79:   Replace `⏎················and·join·Meeting⏎··············` with `and·join·Meeting`                                                                                                                                                                                                               prettier/prettier
[19:19:52.372]   Line 69:38:   Insert `·(`                                                                                                                                                                                                                                                                                      prettier/prettier
[19:19:52.373]   Line 70:29:   Replace `'my-6'` with `"my-6"`                                                                                                                                                                                                                                                                   prettier/prettier
[19:19:52.373]   Line 71:32:   Replace `'md:text-2xl·md:font-bold'>⏎··················Scan·Your·Invite·QR⏎················` with `"md:text-2xl·md:font-bold">Scan·Your·Invite·QR`                                                                                                                                               prettier/prettier
[19:19:52.373]   Line 74:32:   Replace `'md:text-lg'>⏎··················Align·the·QR·to·the·camera⏎················` with `"md:text-lg">Align·the·QR·to·the·camera`                                                                                                                                                             prettier/prettier
[19:19:52.373]   Line 78:13:   Replace `··:` with `)·:·(`                                                                                                                                                                                                                                                                       prettier/prettier
[19:19:52.374]   Line 79:29:   Replace `'my-6'` with `"my-6"`                                                                                                                                                                                                                                                                   prettier/prettier
[19:19:52.375]   Line 80:32:   Replace `'md:text-2xl·md:font-bold'>⏎··················Meeting·Invite·Link·is:⏎················` with `"md:text-2xl·md:font-bold">Meeting·Invite·Link·is:`                                                                                                                                       prettier/prettier
[19:19:52.375]   Line 83:32:   Replace `'md:text-lg'>⏎··················{scanResultWebCam}⏎················` with `"md:text-lg">{scanResultWebCam}`                                                                                                                                                                             prettier/prettier
[19:19:52.375]   Line 87:13:   Insert `)`                                                                                                                                                                                                                                                                                       prettier/prettier
[19:19:52.375]   Line 89:28:   Insert `·(`                                                                                                                                                                                                                                                                                      prettier/prettier
[19:19:52.376]   Line 90:22:   Replace `·className="md:text-xl·px-4·bg-red·py-1·rounded-lg·border·border-danger·my-7"·disabled` with `⏎················className="md:text-xl·px-4·bg-red·py-1·rounded-lg·border·border-danger·my-7"⏎················disabled⏎··············`                                                    prettier/prettier
[19:19:52.376]   Line 93:13:   Replace `··:` with `)·:·(`                                                                                                                                                                                                                                                                       prettier/prettier
[19:19:52.377]   Line 94:22:   Replace `·className="md:text-xl·px-4·bg-emerald-400·py-1·rounded-lg·border·border-danger·my-7"·onClick={joinroomusingid}` with `⏎················className="md:text-xl·px-4·bg-emerald-400·py-1·rounded-lg·border·border-danger·my-7"⏎················onClick={joinroomusingid}⏎··············`  prettier/prettier
[19:19:52.377]   Line 97:13:   Insert `)`                                                                                                                                                                                                                                                                                       prettier/prettier
[19:19:52.377]   Line 102:4:   Insert `;`                                                                                                                                                                                                                                                                                       prettier/prettier
[19:19:52.378]   Line 103:2:   Insert `;`                                                                                                                                                                                                                                                                                       prettier/prettier
[19:19:52.378]   Line 105:22:  Insert `;⏎`                                                                                                                                                                                                                                                                                      prettier/prettier
[19:19:52.378] 
[19:19:52.378] Search for the keywords to learn more about each error.
[19:19:52.378] 
[19:19:52.378] 
[19:19:52.476] Error: Command "npm run build" exited with 1`

**Comment by prasantgupta52** [comment]
@ashavijit please Review it 🥲

**Comment by ashavijit** [comment]
cazz @prasantgupta52

**Pull request merged**
